import type { Metadata } from 'next';
import classNames from 'classnames';
import { Lato, Merriweather } from 'next/font/google';
import '@/styles/app.css';

const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato',
  weight: ['400', '700'],
});

const merriweather = Merriweather({
  subsets: ['latin'],
  variable: '--font-merriweather',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(lato.variable, merriweather.variable)}>
        {children}
      </body>
    </html>
  );
}
